

export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'
export const ROBOT_REQUEST_PENDING = 'ROBOT_REQUEST_PENDING'
export const ROBOT_REQUEST_SUCCESS = 'ROBOT_REQUEST_SUCCESS'
export const ROBOT_REQUEST_FAILED = 'ROBOT_REQUEST_FAILED'
